### ISSUE TITLE
RangeError in GET /works

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#102]
## Error in Search Backend

**RangeError** in **GET /works**
invalid page: 0

[View on Bugsnag](https://app.bugsnag.com/datacite/search-backend/errors/5c1efbb45369d00019fec713?event_id=5c2a0c100032045bed5c0000&i=gh&m=ci)

## Stacktrace

    lib/helpers.rb:128 - pagination_helper
    app.rb:135 - block in <top (required)>

[View full stacktrace](https://app.bugsnag.com/datacite/search-backend/errors/5c1efbb45369d00019fec713?event_id=5c2a0c100032045bed5c0000&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by kjgarza** [comment]
---
title: 'Bug report'
labels: bug
---

Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED!



### Expected Behaviour


Pagination should paginate provided that receive correct page numbers.

### Current Behaviour


When recieicing page  as 0 fails because page 0 doesn't exist

### Steps to Reproduce



1. call https://search.datacite.org/works?source-id=datacite-search-link&year=2017&registered=2018&page=0

### Context (Environment)





IT ha been happening just recently (a week ago)
all the calls come from datacite-search-link

### Hypothesis


Some other application (potentially orcid related) is sending page as 0 or the input for page is being trunckated. 

### Detailed Description


-force that page is always an integereg larger than 0.


### Possible Implementation
