### ISSUE TITLE
Filter data outside `yop` and `current date` in the Search List results

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#132]
In the search results view, the usage metrics displayed need to have filtered out any of the usage counts that were outside the range between "publicationYear" (YOP) and the "currentDate".

This means in an ideal world that when we request metrics "get_metrics" from lagottino, this should be able to be pre-filtered based upon the data it already contains.
Alternatively being able to return some aggregations based upon YOP could then allow filtering within the search.

**Comment by richardhallett** [comment]
Although the index contains obj.publishedDate - This Would need to be used against a filter/query for each of the doi's we specify occurredDate. 
Filtering a date range is easy enough with something like:
```
"range": {
          "occurred_at": {
            "gte": "2018-08-01",
            "lte": "2019-08-01"
          }
        }
```
However to do that you want to be able to specify the gte to be obj.publishedDate, it'd require referencing the document data and this isn't something ES is good at as it's performance intensive to do this kind of sub querying (see joins)

So while I investigated that line of reasoning initially, I think best next step is to go with an alternative of just doing aggregations by YOP and then filtering this within the search (ruby code), while not as performant this is probably the simpler option.
Additionally given that in general most events are going to be after the publication date, the situation of intensive filtering is probably limited.

**Comment by richardhallett** [comment]
After further investigation and discussion with @kjgarza this is actually a very tricky problem.
Attempting to do this within search in some ways misses the point, because the API if asked about usage  should presumably be able to answer with filtered out potential bad usage.

Bad usage being defined as
> all usage events `occurred_at` should be between the DOI `publicationYear` and `current_date`

A filter could have been applied relatively easily to all the event data but this should only apply to usage and not citations which can be outside that range as well as potential other source types.

So instead we need to work on providing just specific filtering to usage source types, the easiest way to do this is to provide an additional separate aggregation of these numbers which are pre-filtered.

To achieve the actual filtering, the only way is through a custom script, this is not as performant, however when dealing with a limited subset of DOI's as is the usecase for search, it should be reasonably fast, also common script indexes do get cached on ES.

This can then be applied to just the aggregation:

```json
"filter": {
  "script": {
      "script": "doc['source_id'].value == 'datacite-usage' && doc['occurred_at'].value.getMillis() >= doc['obj.datePublished'].value.getMillis() && doc['occurred_at'].value.getMillis() < new Date().getTime()"
  }
},
```

Furthermore while a new aggregation will work and solve the immediate problem of this issue, it would probably be easier, that if usage should only be relevant to a period of time, then that filtering should happen before the events are added to the index.

@kjgarza as we discussed this if I've missed anything out of our analysis and solution then please update.

**Comment by richardhallett** [comment]
Stats now exclude data outside 'yop' and 'current date' in the search list results.

**Comment by mfenner** [comment]
Thanks. Agree that going forward we should check usage that goes into the index and exclude events outside of the time range that makes sense. For current date that is very easy, as we can simply reject usage reports for months that are in the future.
