### ISSUE TITLE
Get citations display ready for external testing

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#156]
* updated readme (new screenshot, fixed code climate badges)
* updated Gemfile.lock
* removed puma application server as dev dependency (use webrich instead)
* removed obsolete INCLUDED_RELATION_TYPES
* generate javascript widget using yarn and copy to public folder
* don't use vue widget for list view (unnecessary overhead)
* added test coverage (via https://github.com/crosscite/doi-metadata-search/issues/157)
* standardized language in listing of citations, references and relations
* standardized tab labels
* removed obsolete methods
* cleaned up code formatting (spaces, indendation, etc.)

**Comment by kjgarza** [comment]
https://github.com/crosscite/doi-metadata-search/commit/a659dd042cdd3a62f758ac6f7008940c8b26f323

Actually, I think we will need the `data-metrics-badge` to get the citations in the `Result List view` because of the old approach to show citations in the list, using aggregating citations on lists of DOIs, doesn't work with the *new citations criteria*.

That's the reason why *citations* do no show in the `Result List view.` For example, this item has 8 citations, but the citations are not showing them in the `Result List view`: 

Individual View:  https://search.datacite.org/works/10.5438/0010
Result List view:  https://search.datacite.org/works?query=prefix%3A10.5438
 

The criteria used to be a simple aggregation of ORs conditions but, now, the criteria is an aggregation of ORs and ANDs conditions. That is to say; one will always need to know the DOI in question  AND in which node is to aggregate the citations. Requesting the citations for a list of DOIs won't work using only `aggregations` (that's the old approach). Therefore, using an `aggregation` is not the best way but using a `query` per DOI. The data-metrics-badge makes a `query` to obtain the citations. That's why I was using the `data-metrics-badge.` 

One could use the request for citations using the `query` for the new criteria in the Sinatra APP, but that would mean that the first-page-load would be multiplied by the number of records. Regularly x25, and its blocking. So loading the first page would take forever. 

Using the data-metrics-badge, however (thus the `query`), would do a smaller request, plus is non-blocking and asynchronous. The requests is smaller because it takes advantage of graphql and the data-metrics-badge is making the calls asynchronous all the calls are done in parallel. It is making the first-page-load more efficient. That's why I was using the data-metrics-badge.

**Comment by mfenner** [comment]
We can discuss in our next call. The problem with the above approach is that it is `n+1` problem, i.e. lots of API calls that amongst other things put a significant load on the REST API.
