### ISSUE TITLE
404 contributors page

### ISSUE THREAD

**Issue by kbraak** [crosscite/doi-metadata-search#60]
The link to the creator [Dimitry Brosens](http://search.datacite.org/contributors/0000-0002-0846-9116) on this [dataset](http://search.datacite.org/works/10.15468/LJ0UDQ) leads to a 404. You can confirm his ORCID account is valid [here](http://orcid.org/0000-0002-0846-9116).

![screen shot 2016-09-23 at 11 22 58](https://cloud.githubusercontent.com/assets/5981100/18780964/22b45b2a-8180-11e6-837d-e23fb493361d.png)

A potentially related problem: there are two creators with ORCIDs for this [dataset](http://search.datacite.org/works/10.15468/LJ0UDQ), but only one gets listed in the Contributions sections at the bottom. 

![screen shot 2016-09-23 at 11 25 15](https://cloud.githubusercontent.com/assets/5981100/18781037/6eb57392-8180-11e6-8afb-ca9086032980.png)
![screen shot 2016-09-23 at 11 24 15](https://cloud.githubusercontent.com/assets/5981100/18780999/480f1e14-8180-11e6-95dd-a498c71ad2be.png)

**Comment by mfenner** [comment]
Thank you for opening the issue. The underlying problem is that we are not yet completely merging all DOI<->ORCID links (coming from either the DOI metadata or the Search and Link claiming) in one place. One reason is that we have to update our index, which is a bigger piece of work with some dependencies. But there are other things we can do to improve this in the meantime.
